#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
# Source0 file verified with key 0xE4522DCC9B246FF7 (zdohnal@redhat.com)
#
Name     : cups
Version  : 2.4.10
Release  : 63
URL      : https://github.com/OpenPrinting/cups/releases/download/v2.4.10/cups-2.4.10-source.tar.gz
Source0  : https://github.com/OpenPrinting/cups/releases/download/v2.4.10/cups-2.4.10-source.tar.gz
Source1  : cups.tmpfiles
Source2  : https://github.com/OpenPrinting/cups/releases/download/v2.4.10/cups-2.4.10-source.tar.gz.sig
Source3  : E4522DCC9B246FF7.pkey
Summary  : CUPS
Group    : Development/Tools
License  : Apache-2.0 Zlib
Requires: cups-autostart = %{version}-%{release}
Requires: cups-bin = %{version}-%{release}
Requires: cups-config = %{version}-%{release}
Requires: cups-data = %{version}-%{release}
Requires: cups-lib = %{version}-%{release}
Requires: cups-license = %{version}-%{release}
Requires: cups-man = %{version}-%{release}
Requires: cups-services = %{version}-%{release}
Requires: cups-doc
Requires: poppler-bin
BuildRequires : Linux-PAM-dev
BuildRequires : acl-dev
BuildRequires : buildreq-configure
BuildRequires : dbus-dev
BuildRequires : ghostscript
BuildRequires : ghostscript-dev
BuildRequires : gnupg
BuildRequires : gnutls-dev
BuildRequires : krb5-dev
BuildRequires : libusb-dev
BuildRequires : llvm-dev
BuildRequires : pkgconfig(com_err)
BuildRequires : pkgconfig(zlib)
BuildRequires : systemd-dev
BuildRequires : xdg-utils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-stateless-cupsd.patch
Patch2: 0002-log-to-syslog-by-default.patch
Patch3: 0003-use-clearlinux-pam-policies.patch
Patch4: 0004-dont-modify-os-config-files.patch

%description
CUPS is the standards-based, open source printing system developed by
Apple Inc. and maintained by OpenPrinting for macOS® and other UNIX®-like
operating systems.

%package autostart
Summary: autostart components for the cups package.
Group: Default

%description autostart
autostart components for the cups package.


%package bin
Summary: bin components for the cups package.
Group: Binaries
Requires: cups-data = %{version}-%{release}
Requires: cups-config = %{version}-%{release}
Requires: cups-license = %{version}-%{release}
Requires: cups-services = %{version}-%{release}

%description bin
bin components for the cups package.


%package config
Summary: config components for the cups package.
Group: Default

%description config
config components for the cups package.


%package data
Summary: data components for the cups package.
Group: Data

%description data
data components for the cups package.


%package dev
Summary: dev components for the cups package.
Group: Development
Requires: cups-lib = %{version}-%{release}
Requires: cups-bin = %{version}-%{release}
Requires: cups-data = %{version}-%{release}
Provides: cups-devel = %{version}-%{release}
Requires: cups = %{version}-%{release}

%description dev
dev components for the cups package.


%package doc
Summary: doc components for the cups package.
Group: Documentation
Requires: cups-man = %{version}-%{release}

%description doc
doc components for the cups package.


%package lib
Summary: lib components for the cups package.
Group: Libraries
Requires: cups-data = %{version}-%{release}
Requires: cups-license = %{version}-%{release}

%description lib
lib components for the cups package.


%package license
Summary: license components for the cups package.
Group: Default

%description license
license components for the cups package.


%package man
Summary: man components for the cups package.
Group: Default

%description man
man components for the cups package.


%package services
Summary: services components for the cups package.
Group: Systemd services
Requires: systemd

%description services
services components for the cups package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE3}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE2} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) E4522DCC9B246FF7' gpg.status
%setup -q -n cups-2.4.10
cd %{_builddir}/cups-2.4.10
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
pushd ..
cp -a cups-2.4.10 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719957627
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-system-groups="root wheel lp" \
--enable-gssapi \
--enable-libusb \
--with-dbusdir=/usr/share/dbus-1/ \
--with-rundir=/run/cups
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-system-groups="root wheel lp" \
--enable-gssapi \
--enable-libusb \
--with-dbusdir=/usr/share/dbus-1/ \
--with-rundir=/run/cups
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make unittests

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719957627
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cups
cp %{_builddir}/cups-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/cups/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/cups-%{version}/doc/help/license.html %{buildroot}/usr/share/package-licenses/cups/ba086bb20e20708223f0e789026aabeb7c6ae0cc || :
cp %{_builddir}/cups-%{version}/vcnet/regex/COPYRIGHT %{buildroot}/usr/share/package-licenses/cups/3e1353f170c05e116354014b1f59a7dfbddc4d87 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 STRIPPROG=''
popd
GOAMD64=v2
%make_install STRIPPROG=''
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/cups.conf
## Remove excluded files
rm -f %{buildroot}*/usr/share/doc/cups/help/license.html
## install_append content
make -C tools all
chmod a+x %{buildroot}/usr/bin/cupsd
install -d -m 755 %{buildroot}/usr/share/defaults/etc
cp -R %{buildroot}/etc/* %{buildroot}/usr/share/defaults/etc/
chmod 0644 %{buildroot}/usr/share/defaults/etc/cups/*
install -d -m 0755 %{buildroot}/usr/share/pam.d
install -m 0644 data/cups.pam %{buildroot}/usr/share/pam.d/cups
mkdir -p %{buildroot}/usr/lib/systemd/system/sockets.target.wants
ln -sf ../cups.socket %{buildroot}/usr/lib/systemd/system/sockets.target.wants/cups.socket
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib/cups/backend/ipp
/V3/usr/lib/cups/backend/lpd
/V3/usr/lib/cups/backend/snmp
/V3/usr/lib/cups/backend/socket
/V3/usr/lib/cups/backend/usb
/V3/usr/lib/cups/cgi-bin/admin.cgi
/V3/usr/lib/cups/cgi-bin/classes.cgi
/V3/usr/lib/cups/cgi-bin/help.cgi
/V3/usr/lib/cups/cgi-bin/jobs.cgi
/V3/usr/lib/cups/cgi-bin/printers.cgi
/V3/usr/lib/cups/command/ippevepcl
/V3/usr/lib/cups/command/ippeveps
/V3/usr/lib/cups/daemon/cups-deviced
/V3/usr/lib/cups/daemon/cups-driverd
/V3/usr/lib/cups/daemon/cups-exec
/V3/usr/lib/cups/daemon/cups-lpd
/V3/usr/lib/cups/filter/commandtops
/V3/usr/lib/cups/filter/gziptoany
/V3/usr/lib/cups/filter/pstops
/V3/usr/lib/cups/filter/rastertoepson
/V3/usr/lib/cups/filter/rastertohp
/V3/usr/lib/cups/filter/rastertolabel
/V3/usr/lib/cups/filter/rastertopwg
/V3/usr/lib/cups/monitor/bcp
/V3/usr/lib/cups/monitor/tbcp
/V3/usr/lib/cups/notifier/dbus
/V3/usr/lib/cups/notifier/mailto
/V3/usr/lib/cups/notifier/rss
/usr/lib/cups/backend/http
/usr/lib/cups/backend/https
/usr/lib/cups/backend/ipp
/usr/lib/cups/backend/ipps
/usr/lib/cups/backend/lpd
/usr/lib/cups/backend/snmp
/usr/lib/cups/backend/socket
/usr/lib/cups/backend/usb
/usr/lib/cups/cgi-bin/admin.cgi
/usr/lib/cups/cgi-bin/classes.cgi
/usr/lib/cups/cgi-bin/help.cgi
/usr/lib/cups/cgi-bin/jobs.cgi
/usr/lib/cups/cgi-bin/printers.cgi
/usr/lib/cups/command/ippevepcl
/usr/lib/cups/command/ippeveps
/usr/lib/cups/daemon/cups-deviced
/usr/lib/cups/daemon/cups-driverd
/usr/lib/cups/daemon/cups-exec
/usr/lib/cups/daemon/cups-lpd
/usr/lib/cups/filter/commandtops
/usr/lib/cups/filter/gziptoany
/usr/lib/cups/filter/pstops
/usr/lib/cups/filter/rastertoepson
/usr/lib/cups/filter/rastertohp
/usr/lib/cups/filter/rastertolabel
/usr/lib/cups/filter/rastertopwg
/usr/lib/cups/monitor/bcp
/usr/lib/cups/monitor/tbcp
/usr/lib/cups/notifier/dbus
/usr/lib/cups/notifier/mailto
/usr/lib/cups/notifier/rss

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/sockets.target.wants/cups.socket

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/cancel
/V3/usr/bin/cupsaccept
/V3/usr/bin/cupsctl
/V3/usr/bin/cupsd
/V3/usr/bin/cupsfilter
/V3/usr/bin/cupstestppd
/V3/usr/bin/ippeveprinter
/V3/usr/bin/ipptool
/V3/usr/bin/lp
/V3/usr/bin/lpadmin
/V3/usr/bin/lpc
/V3/usr/bin/lpinfo
/V3/usr/bin/lpmove
/V3/usr/bin/lpoptions
/V3/usr/bin/lpq
/V3/usr/bin/lpr
/V3/usr/bin/lprm
/V3/usr/bin/lpstat
/V3/usr/bin/ppdc
/V3/usr/bin/ppdhtml
/V3/usr/bin/ppdi
/V3/usr/bin/ppdmerge
/V3/usr/bin/ppdpo
/usr/bin/cancel
/usr/bin/cups-config
/usr/bin/cupsaccept
/usr/bin/cupsctl
/usr/bin/cupsd
/usr/bin/cupsdisable
/usr/bin/cupsenable
/usr/bin/cupsfilter
/usr/bin/cupsreject
/usr/bin/cupstestppd
/usr/bin/ippeveprinter
/usr/bin/ipptool
/usr/bin/lp
/usr/bin/lpadmin
/usr/bin/lpc
/usr/bin/lpinfo
/usr/bin/lpmove
/usr/bin/lpoptions
/usr/bin/lpq
/usr/bin/lpr
/usr/bin/lprm
/usr/bin/lpstat
/usr/bin/ppdc
/usr/bin/ppdhtml
/usr/bin/ppdi
/usr/bin/ppdmerge
/usr/bin/ppdpo

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/cups.conf

%files data
%defattr(-,root,root,-)
/usr/share/applications/cups.desktop
/usr/share/cups/drv/sample.drv
/usr/share/cups/examples/color.drv
/usr/share/cups/examples/constraint.drv
/usr/share/cups/examples/custom.drv
/usr/share/cups/examples/grouping.drv
/usr/share/cups/examples/laserjet-basic.drv
/usr/share/cups/examples/laserjet-pjl.drv
/usr/share/cups/examples/minimum.drv
/usr/share/cups/examples/postscript.drv
/usr/share/cups/examples/r300-basic.drv
/usr/share/cups/examples/r300-colorman.drv
/usr/share/cups/examples/r300-remote.drv
/usr/share/cups/ipptool/cancel-current-job.test
/usr/share/cups/ipptool/color.jpg
/usr/share/cups/ipptool/create-job-format.test
/usr/share/cups/ipptool/create-job-sheets.test
/usr/share/cups/ipptool/create-job-timeout.test
/usr/share/cups/ipptool/create-job.test
/usr/share/cups/ipptool/create-printer-subscription.test
/usr/share/cups/ipptool/cups-create-local-printer.test
/usr/share/cups/ipptool/document-a4.pdf
/usr/share/cups/ipptool/document-a4.ps
/usr/share/cups/ipptool/document-letter.pdf
/usr/share/cups/ipptool/document-letter.ps
/usr/share/cups/ipptool/fax-job.test
/usr/share/cups/ipptool/get-completed-jobs.test
/usr/share/cups/ipptool/get-devices.test
/usr/share/cups/ipptool/get-job-attributes.test
/usr/share/cups/ipptool/get-job-attributes2.test
/usr/share/cups/ipptool/get-job-template-attributes.test
/usr/share/cups/ipptool/get-jobs.test
/usr/share/cups/ipptool/get-notifications.test
/usr/share/cups/ipptool/get-ppd-printer.test
/usr/share/cups/ipptool/get-ppd.test
/usr/share/cups/ipptool/get-ppds-drv-only.test
/usr/share/cups/ipptool/get-ppds-language.test
/usr/share/cups/ipptool/get-ppds-make-and-model.test
/usr/share/cups/ipptool/get-ppds-make.test
/usr/share/cups/ipptool/get-ppds-product.test
/usr/share/cups/ipptool/get-ppds-psversion.test
/usr/share/cups/ipptool/get-ppds.test
/usr/share/cups/ipptool/get-printer-attributes-suite.test
/usr/share/cups/ipptool/get-printer-attributes.test
/usr/share/cups/ipptool/get-printer-description-attributes.test
/usr/share/cups/ipptool/get-printers-printer-id.test
/usr/share/cups/ipptool/get-printers.test
/usr/share/cups/ipptool/get-subscriptions.test
/usr/share/cups/ipptool/gray.jpg
/usr/share/cups/ipptool/identify-printer-display.test
/usr/share/cups/ipptool/identify-printer-multiple.test
/usr/share/cups/ipptool/identify-printer.test
/usr/share/cups/ipptool/ipp-1.1.test
/usr/share/cups/ipptool/ipp-2.0.test
/usr/share/cups/ipptool/ipp-2.1.test
/usr/share/cups/ipptool/ipp-2.2.test
/usr/share/cups/ipptool/ipp-backend.test
/usr/share/cups/ipptool/ipp-everywhere.test
/usr/share/cups/ipptool/onepage-a4.pdf
/usr/share/cups/ipptool/onepage-a4.ps
/usr/share/cups/ipptool/onepage-letter.pdf
/usr/share/cups/ipptool/onepage-letter.ps
/usr/share/cups/ipptool/print-job-and-wait.test
/usr/share/cups/ipptool/print-job-deflate.test
/usr/share/cups/ipptool/print-job-gzip.test
/usr/share/cups/ipptool/print-job-hold.test
/usr/share/cups/ipptool/print-job-letter.test
/usr/share/cups/ipptool/print-job-manual.test
/usr/share/cups/ipptool/print-job-media-col.test
/usr/share/cups/ipptool/print-job-media-needed.test
/usr/share/cups/ipptool/print-job-password.test
/usr/share/cups/ipptool/print-job.test
/usr/share/cups/ipptool/print-uri.test
/usr/share/cups/ipptool/set-attrs-hold.test
/usr/share/cups/ipptool/testfile.jpg
/usr/share/cups/ipptool/testfile.pcl
/usr/share/cups/ipptool/testfile.pdf
/usr/share/cups/ipptool/testfile.ps
/usr/share/cups/ipptool/testfile.txt
/usr/share/cups/ipptool/validate-job.test
/usr/share/cups/mime/mime.convs
/usr/share/cups/mime/mime.types
/usr/share/cups/ppdc/epson.h
/usr/share/cups/ppdc/font.defs
/usr/share/cups/ppdc/hp.h
/usr/share/cups/ppdc/label.h
/usr/share/cups/ppdc/media.defs
/usr/share/cups/ppdc/raster.defs
/usr/share/cups/templates/add-class.tmpl
/usr/share/cups/templates/add-printer.tmpl
/usr/share/cups/templates/admin.tmpl
/usr/share/cups/templates/choose-device.tmpl
/usr/share/cups/templates/choose-make.tmpl
/usr/share/cups/templates/choose-model.tmpl
/usr/share/cups/templates/choose-serial.tmpl
/usr/share/cups/templates/choose-uri.tmpl
/usr/share/cups/templates/class-added.tmpl
/usr/share/cups/templates/class-confirm.tmpl
/usr/share/cups/templates/class-deleted.tmpl
/usr/share/cups/templates/class-jobs-header.tmpl
/usr/share/cups/templates/class-modified.tmpl
/usr/share/cups/templates/class.tmpl
/usr/share/cups/templates/classes-header.tmpl
/usr/share/cups/templates/classes.tmpl
/usr/share/cups/templates/command.tmpl
/usr/share/cups/templates/da/add-class.tmpl
/usr/share/cups/templates/da/add-printer.tmpl
/usr/share/cups/templates/da/admin.tmpl
/usr/share/cups/templates/da/choose-device.tmpl
/usr/share/cups/templates/da/choose-make.tmpl
/usr/share/cups/templates/da/choose-model.tmpl
/usr/share/cups/templates/da/choose-serial.tmpl
/usr/share/cups/templates/da/choose-uri.tmpl
/usr/share/cups/templates/da/class-added.tmpl
/usr/share/cups/templates/da/class-confirm.tmpl
/usr/share/cups/templates/da/class-deleted.tmpl
/usr/share/cups/templates/da/class-jobs-header.tmpl
/usr/share/cups/templates/da/class-modified.tmpl
/usr/share/cups/templates/da/class.tmpl
/usr/share/cups/templates/da/classes-header.tmpl
/usr/share/cups/templates/da/classes.tmpl
/usr/share/cups/templates/da/command.tmpl
/usr/share/cups/templates/da/edit-config.tmpl
/usr/share/cups/templates/da/error-op.tmpl
/usr/share/cups/templates/da/error.tmpl
/usr/share/cups/templates/da/header.tmpl
/usr/share/cups/templates/da/help-header.tmpl
/usr/share/cups/templates/da/help-printable.tmpl
/usr/share/cups/templates/da/help-trailer.tmpl
/usr/share/cups/templates/da/job-cancel.tmpl
/usr/share/cups/templates/da/job-hold.tmpl
/usr/share/cups/templates/da/job-move.tmpl
/usr/share/cups/templates/da/job-moved.tmpl
/usr/share/cups/templates/da/job-release.tmpl
/usr/share/cups/templates/da/job-restart.tmpl
/usr/share/cups/templates/da/jobs-header.tmpl
/usr/share/cups/templates/da/jobs.tmpl
/usr/share/cups/templates/da/list-available-printers.tmpl
/usr/share/cups/templates/da/modify-class.tmpl
/usr/share/cups/templates/da/modify-printer.tmpl
/usr/share/cups/templates/da/norestart.tmpl
/usr/share/cups/templates/da/option-boolean.tmpl
/usr/share/cups/templates/da/option-conflict.tmpl
/usr/share/cups/templates/da/option-header.tmpl
/usr/share/cups/templates/da/option-pickmany.tmpl
/usr/share/cups/templates/da/option-pickone.tmpl
/usr/share/cups/templates/da/option-trailer.tmpl
/usr/share/cups/templates/da/pager.tmpl
/usr/share/cups/templates/da/printer-accept.tmpl
/usr/share/cups/templates/da/printer-added.tmpl
/usr/share/cups/templates/da/printer-cancel-jobs.tmpl
/usr/share/cups/templates/da/printer-configured.tmpl
/usr/share/cups/templates/da/printer-confirm.tmpl
/usr/share/cups/templates/da/printer-default.tmpl
/usr/share/cups/templates/da/printer-deleted.tmpl
/usr/share/cups/templates/da/printer-jobs-header.tmpl
/usr/share/cups/templates/da/printer-modified.tmpl
/usr/share/cups/templates/da/printer-reject.tmpl
/usr/share/cups/templates/da/printer-start.tmpl
/usr/share/cups/templates/da/printer-stop.tmpl
/usr/share/cups/templates/da/printer.tmpl
/usr/share/cups/templates/da/printers-header.tmpl
/usr/share/cups/templates/da/printers.tmpl
/usr/share/cups/templates/da/restart.tmpl
/usr/share/cups/templates/da/search.tmpl
/usr/share/cups/templates/da/set-printer-options-header.tmpl
/usr/share/cups/templates/da/set-printer-options-trailer.tmpl
/usr/share/cups/templates/da/test-page.tmpl
/usr/share/cups/templates/da/trailer.tmpl
/usr/share/cups/templates/da/users.tmpl
/usr/share/cups/templates/de/add-class.tmpl
/usr/share/cups/templates/de/add-printer.tmpl
/usr/share/cups/templates/de/admin.tmpl
/usr/share/cups/templates/de/choose-device.tmpl
/usr/share/cups/templates/de/choose-make.tmpl
/usr/share/cups/templates/de/choose-model.tmpl
/usr/share/cups/templates/de/choose-serial.tmpl
/usr/share/cups/templates/de/choose-uri.tmpl
/usr/share/cups/templates/de/class-added.tmpl
/usr/share/cups/templates/de/class-confirm.tmpl
/usr/share/cups/templates/de/class-deleted.tmpl
/usr/share/cups/templates/de/class-jobs-header.tmpl
/usr/share/cups/templates/de/class-modified.tmpl
/usr/share/cups/templates/de/class.tmpl
/usr/share/cups/templates/de/classes-header.tmpl
/usr/share/cups/templates/de/classes.tmpl
/usr/share/cups/templates/de/command.tmpl
/usr/share/cups/templates/de/edit-config.tmpl
/usr/share/cups/templates/de/error-op.tmpl
/usr/share/cups/templates/de/error.tmpl
/usr/share/cups/templates/de/header.tmpl
/usr/share/cups/templates/de/help-header.tmpl
/usr/share/cups/templates/de/help-printable.tmpl
/usr/share/cups/templates/de/help-trailer.tmpl
/usr/share/cups/templates/de/job-cancel.tmpl
/usr/share/cups/templates/de/job-hold.tmpl
/usr/share/cups/templates/de/job-move.tmpl
/usr/share/cups/templates/de/job-moved.tmpl
/usr/share/cups/templates/de/job-release.tmpl
/usr/share/cups/templates/de/job-restart.tmpl
/usr/share/cups/templates/de/jobs-header.tmpl
/usr/share/cups/templates/de/jobs.tmpl
/usr/share/cups/templates/de/list-available-printers.tmpl
/usr/share/cups/templates/de/modify-class.tmpl
/usr/share/cups/templates/de/modify-printer.tmpl
/usr/share/cups/templates/de/norestart.tmpl
/usr/share/cups/templates/de/option-boolean.tmpl
/usr/share/cups/templates/de/option-conflict.tmpl
/usr/share/cups/templates/de/option-header.tmpl
/usr/share/cups/templates/de/option-pickmany.tmpl
/usr/share/cups/templates/de/option-pickone.tmpl
/usr/share/cups/templates/de/option-trailer.tmpl
/usr/share/cups/templates/de/pager.tmpl
/usr/share/cups/templates/de/printer-accept.tmpl
/usr/share/cups/templates/de/printer-added.tmpl
/usr/share/cups/templates/de/printer-cancel-jobs.tmpl
/usr/share/cups/templates/de/printer-configured.tmpl
/usr/share/cups/templates/de/printer-confirm.tmpl
/usr/share/cups/templates/de/printer-default.tmpl
/usr/share/cups/templates/de/printer-deleted.tmpl
/usr/share/cups/templates/de/printer-jobs-header.tmpl
/usr/share/cups/templates/de/printer-modified.tmpl
/usr/share/cups/templates/de/printer-reject.tmpl
/usr/share/cups/templates/de/printer-start.tmpl
/usr/share/cups/templates/de/printer-stop.tmpl
/usr/share/cups/templates/de/printer.tmpl
/usr/share/cups/templates/de/printers-header.tmpl
/usr/share/cups/templates/de/printers.tmpl
/usr/share/cups/templates/de/restart.tmpl
/usr/share/cups/templates/de/search.tmpl
/usr/share/cups/templates/de/set-printer-options-header.tmpl
/usr/share/cups/templates/de/set-printer-options-trailer.tmpl
/usr/share/cups/templates/de/test-page.tmpl
/usr/share/cups/templates/de/trailer.tmpl
/usr/share/cups/templates/de/users.tmpl
/usr/share/cups/templates/edit-config.tmpl
/usr/share/cups/templates/error-op.tmpl
/usr/share/cups/templates/error.tmpl
/usr/share/cups/templates/es/add-class.tmpl
/usr/share/cups/templates/es/add-printer.tmpl
/usr/share/cups/templates/es/admin.tmpl
/usr/share/cups/templates/es/choose-device.tmpl
/usr/share/cups/templates/es/choose-make.tmpl
/usr/share/cups/templates/es/choose-model.tmpl
/usr/share/cups/templates/es/choose-serial.tmpl
/usr/share/cups/templates/es/choose-uri.tmpl
/usr/share/cups/templates/es/class-added.tmpl
/usr/share/cups/templates/es/class-confirm.tmpl
/usr/share/cups/templates/es/class-deleted.tmpl
/usr/share/cups/templates/es/class-jobs-header.tmpl
/usr/share/cups/templates/es/class-modified.tmpl
/usr/share/cups/templates/es/class.tmpl
/usr/share/cups/templates/es/classes-header.tmpl
/usr/share/cups/templates/es/classes.tmpl
/usr/share/cups/templates/es/command.tmpl
/usr/share/cups/templates/es/edit-config.tmpl
/usr/share/cups/templates/es/error-op.tmpl
/usr/share/cups/templates/es/error.tmpl
/usr/share/cups/templates/es/header.tmpl
/usr/share/cups/templates/es/help-header.tmpl
/usr/share/cups/templates/es/help-printable.tmpl
/usr/share/cups/templates/es/help-trailer.tmpl
/usr/share/cups/templates/es/job-cancel.tmpl
/usr/share/cups/templates/es/job-hold.tmpl
/usr/share/cups/templates/es/job-move.tmpl
/usr/share/cups/templates/es/job-moved.tmpl
/usr/share/cups/templates/es/job-release.tmpl
/usr/share/cups/templates/es/job-restart.tmpl
/usr/share/cups/templates/es/jobs-header.tmpl
/usr/share/cups/templates/es/jobs.tmpl
/usr/share/cups/templates/es/list-available-printers.tmpl
/usr/share/cups/templates/es/modify-class.tmpl
/usr/share/cups/templates/es/modify-printer.tmpl
/usr/share/cups/templates/es/norestart.tmpl
/usr/share/cups/templates/es/option-boolean.tmpl
/usr/share/cups/templates/es/option-conflict.tmpl
/usr/share/cups/templates/es/option-header.tmpl
/usr/share/cups/templates/es/option-pickmany.tmpl
/usr/share/cups/templates/es/option-pickone.tmpl
/usr/share/cups/templates/es/option-trailer.tmpl
/usr/share/cups/templates/es/pager.tmpl
/usr/share/cups/templates/es/printer-accept.tmpl
/usr/share/cups/templates/es/printer-added.tmpl
/usr/share/cups/templates/es/printer-cancel-jobs.tmpl
/usr/share/cups/templates/es/printer-configured.tmpl
/usr/share/cups/templates/es/printer-confirm.tmpl
/usr/share/cups/templates/es/printer-default.tmpl
/usr/share/cups/templates/es/printer-deleted.tmpl
/usr/share/cups/templates/es/printer-jobs-header.tmpl
/usr/share/cups/templates/es/printer-modified.tmpl
/usr/share/cups/templates/es/printer-reject.tmpl
/usr/share/cups/templates/es/printer-start.tmpl
/usr/share/cups/templates/es/printer-stop.tmpl
/usr/share/cups/templates/es/printer.tmpl
/usr/share/cups/templates/es/printers-header.tmpl
/usr/share/cups/templates/es/printers.tmpl
/usr/share/cups/templates/es/restart.tmpl
/usr/share/cups/templates/es/search.tmpl
/usr/share/cups/templates/es/set-printer-options-header.tmpl
/usr/share/cups/templates/es/set-printer-options-trailer.tmpl
/usr/share/cups/templates/es/test-page.tmpl
/usr/share/cups/templates/es/trailer.tmpl
/usr/share/cups/templates/es/users.tmpl
/usr/share/cups/templates/fr/add-class.tmpl
/usr/share/cups/templates/fr/add-printer.tmpl
/usr/share/cups/templates/fr/admin.tmpl
/usr/share/cups/templates/fr/choose-device.tmpl
/usr/share/cups/templates/fr/choose-make.tmpl
/usr/share/cups/templates/fr/choose-model.tmpl
/usr/share/cups/templates/fr/choose-serial.tmpl
/usr/share/cups/templates/fr/choose-uri.tmpl
/usr/share/cups/templates/fr/class-added.tmpl
/usr/share/cups/templates/fr/class-confirm.tmpl
/usr/share/cups/templates/fr/class-deleted.tmpl
/usr/share/cups/templates/fr/class-jobs-header.tmpl
/usr/share/cups/templates/fr/class-modified.tmpl
/usr/share/cups/templates/fr/class.tmpl
/usr/share/cups/templates/fr/classes-header.tmpl
/usr/share/cups/templates/fr/classes.tmpl
/usr/share/cups/templates/fr/command.tmpl
/usr/share/cups/templates/fr/edit-config.tmpl
/usr/share/cups/templates/fr/error-op.tmpl
/usr/share/cups/templates/fr/error.tmpl
/usr/share/cups/templates/fr/header.tmpl
/usr/share/cups/templates/fr/help-header.tmpl
/usr/share/cups/templates/fr/help-printable.tmpl
/usr/share/cups/templates/fr/help-trailer.tmpl
/usr/share/cups/templates/fr/job-cancel.tmpl
/usr/share/cups/templates/fr/job-hold.tmpl
/usr/share/cups/templates/fr/job-move.tmpl
/usr/share/cups/templates/fr/job-moved.tmpl
/usr/share/cups/templates/fr/job-release.tmpl
/usr/share/cups/templates/fr/job-restart.tmpl
/usr/share/cups/templates/fr/jobs-header.tmpl
/usr/share/cups/templates/fr/jobs.tmpl
/usr/share/cups/templates/fr/list-available-printers.tmpl
/usr/share/cups/templates/fr/modify-class.tmpl
/usr/share/cups/templates/fr/modify-printer.tmpl
/usr/share/cups/templates/fr/norestart.tmpl
/usr/share/cups/templates/fr/option-boolean.tmpl
/usr/share/cups/templates/fr/option-conflict.tmpl
/usr/share/cups/templates/fr/option-header.tmpl
/usr/share/cups/templates/fr/option-pickmany.tmpl
/usr/share/cups/templates/fr/option-pickone.tmpl
/usr/share/cups/templates/fr/option-trailer.tmpl
/usr/share/cups/templates/fr/pager.tmpl
/usr/share/cups/templates/fr/printer-accept.tmpl
/usr/share/cups/templates/fr/printer-added.tmpl
/usr/share/cups/templates/fr/printer-cancel-jobs.tmpl
/usr/share/cups/templates/fr/printer-configured.tmpl
/usr/share/cups/templates/fr/printer-confirm.tmpl
/usr/share/cups/templates/fr/printer-default.tmpl
/usr/share/cups/templates/fr/printer-deleted.tmpl
/usr/share/cups/templates/fr/printer-jobs-header.tmpl
/usr/share/cups/templates/fr/printer-modified.tmpl
/usr/share/cups/templates/fr/printer-reject.tmpl
/usr/share/cups/templates/fr/printer-start.tmpl
/usr/share/cups/templates/fr/printer-stop.tmpl
/usr/share/cups/templates/fr/printer.tmpl
/usr/share/cups/templates/fr/printers-header.tmpl
/usr/share/cups/templates/fr/printers.tmpl
/usr/share/cups/templates/fr/restart.tmpl
/usr/share/cups/templates/fr/search.tmpl
/usr/share/cups/templates/fr/set-printer-options-header.tmpl
/usr/share/cups/templates/fr/set-printer-options-trailer.tmpl
/usr/share/cups/templates/fr/test-page.tmpl
/usr/share/cups/templates/fr/trailer.tmpl
/usr/share/cups/templates/fr/users.tmpl
/usr/share/cups/templates/header.tmpl
/usr/share/cups/templates/help-header.tmpl
/usr/share/cups/templates/help-printable.tmpl
/usr/share/cups/templates/help-trailer.tmpl
/usr/share/cups/templates/ja/add-class.tmpl
/usr/share/cups/templates/ja/add-printer.tmpl
/usr/share/cups/templates/ja/admin.tmpl
/usr/share/cups/templates/ja/choose-device.tmpl
/usr/share/cups/templates/ja/choose-make.tmpl
/usr/share/cups/templates/ja/choose-model.tmpl
/usr/share/cups/templates/ja/choose-serial.tmpl
/usr/share/cups/templates/ja/choose-uri.tmpl
/usr/share/cups/templates/ja/class-added.tmpl
/usr/share/cups/templates/ja/class-confirm.tmpl
/usr/share/cups/templates/ja/class-deleted.tmpl
/usr/share/cups/templates/ja/class-jobs-header.tmpl
/usr/share/cups/templates/ja/class-modified.tmpl
/usr/share/cups/templates/ja/class.tmpl
/usr/share/cups/templates/ja/classes-header.tmpl
/usr/share/cups/templates/ja/classes.tmpl
/usr/share/cups/templates/ja/command.tmpl
/usr/share/cups/templates/ja/edit-config.tmpl
/usr/share/cups/templates/ja/error-op.tmpl
/usr/share/cups/templates/ja/error.tmpl
/usr/share/cups/templates/ja/header.tmpl
/usr/share/cups/templates/ja/help-header.tmpl
/usr/share/cups/templates/ja/help-printable.tmpl
/usr/share/cups/templates/ja/help-trailer.tmpl
/usr/share/cups/templates/ja/job-cancel.tmpl
/usr/share/cups/templates/ja/job-hold.tmpl
/usr/share/cups/templates/ja/job-move.tmpl
/usr/share/cups/templates/ja/job-moved.tmpl
/usr/share/cups/templates/ja/job-release.tmpl
/usr/share/cups/templates/ja/job-restart.tmpl
/usr/share/cups/templates/ja/jobs-header.tmpl
/usr/share/cups/templates/ja/jobs.tmpl
/usr/share/cups/templates/ja/list-available-printers.tmpl
/usr/share/cups/templates/ja/modify-class.tmpl
/usr/share/cups/templates/ja/modify-printer.tmpl
/usr/share/cups/templates/ja/norestart.tmpl
/usr/share/cups/templates/ja/option-boolean.tmpl
/usr/share/cups/templates/ja/option-conflict.tmpl
/usr/share/cups/templates/ja/option-header.tmpl
/usr/share/cups/templates/ja/option-pickmany.tmpl
/usr/share/cups/templates/ja/option-pickone.tmpl
/usr/share/cups/templates/ja/option-trailer.tmpl
/usr/share/cups/templates/ja/pager.tmpl
/usr/share/cups/templates/ja/printer-accept.tmpl
/usr/share/cups/templates/ja/printer-added.tmpl
/usr/share/cups/templates/ja/printer-cancel-jobs.tmpl
/usr/share/cups/templates/ja/printer-configured.tmpl
/usr/share/cups/templates/ja/printer-confirm.tmpl
/usr/share/cups/templates/ja/printer-default.tmpl
/usr/share/cups/templates/ja/printer-deleted.tmpl
/usr/share/cups/templates/ja/printer-jobs-header.tmpl
/usr/share/cups/templates/ja/printer-modified.tmpl
/usr/share/cups/templates/ja/printer-reject.tmpl
/usr/share/cups/templates/ja/printer-start.tmpl
/usr/share/cups/templates/ja/printer-stop.tmpl
/usr/share/cups/templates/ja/printer.tmpl
/usr/share/cups/templates/ja/printers-header.tmpl
/usr/share/cups/templates/ja/printers.tmpl
/usr/share/cups/templates/ja/restart.tmpl
/usr/share/cups/templates/ja/search.tmpl
/usr/share/cups/templates/ja/set-printer-options-header.tmpl
/usr/share/cups/templates/ja/set-printer-options-trailer.tmpl
/usr/share/cups/templates/ja/test-page.tmpl
/usr/share/cups/templates/ja/trailer.tmpl
/usr/share/cups/templates/ja/users.tmpl
/usr/share/cups/templates/job-cancel.tmpl
/usr/share/cups/templates/job-hold.tmpl
/usr/share/cups/templates/job-move.tmpl
/usr/share/cups/templates/job-moved.tmpl
/usr/share/cups/templates/job-release.tmpl
/usr/share/cups/templates/job-restart.tmpl
/usr/share/cups/templates/jobs-header.tmpl
/usr/share/cups/templates/jobs.tmpl
/usr/share/cups/templates/list-available-printers.tmpl
/usr/share/cups/templates/modify-class.tmpl
/usr/share/cups/templates/modify-printer.tmpl
/usr/share/cups/templates/norestart.tmpl
/usr/share/cups/templates/option-boolean.tmpl
/usr/share/cups/templates/option-conflict.tmpl
/usr/share/cups/templates/option-header.tmpl
/usr/share/cups/templates/option-pickmany.tmpl
/usr/share/cups/templates/option-pickone.tmpl
/usr/share/cups/templates/option-trailer.tmpl
/usr/share/cups/templates/pager.tmpl
/usr/share/cups/templates/printer-accept.tmpl
/usr/share/cups/templates/printer-added.tmpl
/usr/share/cups/templates/printer-cancel-jobs.tmpl
/usr/share/cups/templates/printer-configured.tmpl
/usr/share/cups/templates/printer-confirm.tmpl
/usr/share/cups/templates/printer-default.tmpl
/usr/share/cups/templates/printer-deleted.tmpl
/usr/share/cups/templates/printer-jobs-header.tmpl
/usr/share/cups/templates/printer-modified.tmpl
/usr/share/cups/templates/printer-reject.tmpl
/usr/share/cups/templates/printer-start.tmpl
/usr/share/cups/templates/printer-stop.tmpl
/usr/share/cups/templates/printer.tmpl
/usr/share/cups/templates/printers-header.tmpl
/usr/share/cups/templates/printers.tmpl
/usr/share/cups/templates/pt_BR/add-class.tmpl
/usr/share/cups/templates/pt_BR/add-printer.tmpl
/usr/share/cups/templates/pt_BR/admin.tmpl
/usr/share/cups/templates/pt_BR/choose-device.tmpl
/usr/share/cups/templates/pt_BR/choose-make.tmpl
/usr/share/cups/templates/pt_BR/choose-model.tmpl
/usr/share/cups/templates/pt_BR/choose-serial.tmpl
/usr/share/cups/templates/pt_BR/choose-uri.tmpl
/usr/share/cups/templates/pt_BR/class-added.tmpl
/usr/share/cups/templates/pt_BR/class-confirm.tmpl
/usr/share/cups/templates/pt_BR/class-deleted.tmpl
/usr/share/cups/templates/pt_BR/class-jobs-header.tmpl
/usr/share/cups/templates/pt_BR/class-modified.tmpl
/usr/share/cups/templates/pt_BR/class.tmpl
/usr/share/cups/templates/pt_BR/classes-header.tmpl
/usr/share/cups/templates/pt_BR/classes.tmpl
/usr/share/cups/templates/pt_BR/command.tmpl
/usr/share/cups/templates/pt_BR/edit-config.tmpl
/usr/share/cups/templates/pt_BR/error-op.tmpl
/usr/share/cups/templates/pt_BR/error.tmpl
/usr/share/cups/templates/pt_BR/header.tmpl
/usr/share/cups/templates/pt_BR/help-header.tmpl
/usr/share/cups/templates/pt_BR/help-printable.tmpl
/usr/share/cups/templates/pt_BR/help-trailer.tmpl
/usr/share/cups/templates/pt_BR/job-cancel.tmpl
/usr/share/cups/templates/pt_BR/job-hold.tmpl
/usr/share/cups/templates/pt_BR/job-move.tmpl
/usr/share/cups/templates/pt_BR/job-moved.tmpl
/usr/share/cups/templates/pt_BR/job-release.tmpl
/usr/share/cups/templates/pt_BR/job-restart.tmpl
/usr/share/cups/templates/pt_BR/jobs-header.tmpl
/usr/share/cups/templates/pt_BR/jobs.tmpl
/usr/share/cups/templates/pt_BR/list-available-printers.tmpl
/usr/share/cups/templates/pt_BR/modify-class.tmpl
/usr/share/cups/templates/pt_BR/modify-printer.tmpl
/usr/share/cups/templates/pt_BR/norestart.tmpl
/usr/share/cups/templates/pt_BR/option-boolean.tmpl
/usr/share/cups/templates/pt_BR/option-conflict.tmpl
/usr/share/cups/templates/pt_BR/option-header.tmpl
/usr/share/cups/templates/pt_BR/option-pickmany.tmpl
/usr/share/cups/templates/pt_BR/option-pickone.tmpl
/usr/share/cups/templates/pt_BR/option-trailer.tmpl
/usr/share/cups/templates/pt_BR/pager.tmpl
/usr/share/cups/templates/pt_BR/printer-accept.tmpl
/usr/share/cups/templates/pt_BR/printer-added.tmpl
/usr/share/cups/templates/pt_BR/printer-cancel-jobs.tmpl
/usr/share/cups/templates/pt_BR/printer-configured.tmpl
/usr/share/cups/templates/pt_BR/printer-confirm.tmpl
/usr/share/cups/templates/pt_BR/printer-default.tmpl
/usr/share/cups/templates/pt_BR/printer-deleted.tmpl
/usr/share/cups/templates/pt_BR/printer-jobs-header.tmpl
/usr/share/cups/templates/pt_BR/printer-modified.tmpl
/usr/share/cups/templates/pt_BR/printer-reject.tmpl
/usr/share/cups/templates/pt_BR/printer-start.tmpl
/usr/share/cups/templates/pt_BR/printer-stop.tmpl
/usr/share/cups/templates/pt_BR/printer.tmpl
/usr/share/cups/templates/pt_BR/printers-header.tmpl
/usr/share/cups/templates/pt_BR/printers.tmpl
/usr/share/cups/templates/pt_BR/restart.tmpl
/usr/share/cups/templates/pt_BR/search.tmpl
/usr/share/cups/templates/pt_BR/set-printer-options-header.tmpl
/usr/share/cups/templates/pt_BR/set-printer-options-trailer.tmpl
/usr/share/cups/templates/pt_BR/test-page.tmpl
/usr/share/cups/templates/pt_BR/trailer.tmpl
/usr/share/cups/templates/pt_BR/users.tmpl
/usr/share/cups/templates/restart.tmpl
/usr/share/cups/templates/ru/add-class.tmpl
/usr/share/cups/templates/ru/add-printer.tmpl
/usr/share/cups/templates/ru/admin.tmpl
/usr/share/cups/templates/ru/choose-device.tmpl
/usr/share/cups/templates/ru/choose-make.tmpl
/usr/share/cups/templates/ru/choose-model.tmpl
/usr/share/cups/templates/ru/choose-serial.tmpl
/usr/share/cups/templates/ru/choose-uri.tmpl
/usr/share/cups/templates/ru/class-added.tmpl
/usr/share/cups/templates/ru/class-confirm.tmpl
/usr/share/cups/templates/ru/class-deleted.tmpl
/usr/share/cups/templates/ru/class-jobs-header.tmpl
/usr/share/cups/templates/ru/class-modified.tmpl
/usr/share/cups/templates/ru/class.tmpl
/usr/share/cups/templates/ru/classes-header.tmpl
/usr/share/cups/templates/ru/classes.tmpl
/usr/share/cups/templates/ru/command.tmpl
/usr/share/cups/templates/ru/edit-config.tmpl
/usr/share/cups/templates/ru/error-op.tmpl
/usr/share/cups/templates/ru/error.tmpl
/usr/share/cups/templates/ru/header.tmpl
/usr/share/cups/templates/ru/help-header.tmpl
/usr/share/cups/templates/ru/help-printable.tmpl
/usr/share/cups/templates/ru/help-trailer.tmpl
/usr/share/cups/templates/ru/job-cancel.tmpl
/usr/share/cups/templates/ru/job-hold.tmpl
/usr/share/cups/templates/ru/job-move.tmpl
/usr/share/cups/templates/ru/job-moved.tmpl
/usr/share/cups/templates/ru/job-release.tmpl
/usr/share/cups/templates/ru/job-restart.tmpl
/usr/share/cups/templates/ru/jobs-header.tmpl
/usr/share/cups/templates/ru/jobs.tmpl
/usr/share/cups/templates/ru/list-available-printers.tmpl
/usr/share/cups/templates/ru/modify-class.tmpl
/usr/share/cups/templates/ru/modify-printer.tmpl
/usr/share/cups/templates/ru/norestart.tmpl
/usr/share/cups/templates/ru/option-boolean.tmpl
/usr/share/cups/templates/ru/option-conflict.tmpl
/usr/share/cups/templates/ru/option-header.tmpl
/usr/share/cups/templates/ru/option-pickmany.tmpl
/usr/share/cups/templates/ru/option-pickone.tmpl
/usr/share/cups/templates/ru/option-trailer.tmpl
/usr/share/cups/templates/ru/pager.tmpl
/usr/share/cups/templates/ru/printer-accept.tmpl
/usr/share/cups/templates/ru/printer-added.tmpl
/usr/share/cups/templates/ru/printer-cancel-jobs.tmpl
/usr/share/cups/templates/ru/printer-configured.tmpl
/usr/share/cups/templates/ru/printer-confirm.tmpl
/usr/share/cups/templates/ru/printer-default.tmpl
/usr/share/cups/templates/ru/printer-deleted.tmpl
/usr/share/cups/templates/ru/printer-jobs-header.tmpl
/usr/share/cups/templates/ru/printer-modified.tmpl
/usr/share/cups/templates/ru/printer-reject.tmpl
/usr/share/cups/templates/ru/printer-start.tmpl
/usr/share/cups/templates/ru/printer-stop.tmpl
/usr/share/cups/templates/ru/printer.tmpl
/usr/share/cups/templates/ru/printers-header.tmpl
/usr/share/cups/templates/ru/printers.tmpl
/usr/share/cups/templates/ru/restart.tmpl
/usr/share/cups/templates/ru/search.tmpl
/usr/share/cups/templates/ru/set-printer-options-header.tmpl
/usr/share/cups/templates/ru/set-printer-options-trailer.tmpl
/usr/share/cups/templates/ru/test-page.tmpl
/usr/share/cups/templates/ru/trailer.tmpl
/usr/share/cups/templates/ru/users.tmpl
/usr/share/cups/templates/search.tmpl
/usr/share/cups/templates/set-printer-options-header.tmpl
/usr/share/cups/templates/set-printer-options-trailer.tmpl
/usr/share/cups/templates/test-page.tmpl
/usr/share/cups/templates/trailer.tmpl
/usr/share/cups/templates/users.tmpl
/usr/share/cups/usb/org.cups.usb-quirks
/usr/share/dbus-1/system.d/cups.conf
/usr/share/defaults/etc/cups/cups-files.conf
/usr/share/defaults/etc/cups/cups-files.conf.default
/usr/share/defaults/etc/cups/cupsd.conf
/usr/share/defaults/etc/cups/cupsd.conf.default
/usr/share/defaults/etc/cups/snmp.conf
/usr/share/defaults/etc/cups/snmp.conf.default
/usr/share/icons/hicolor/128x128/apps/cups.png
/usr/share/icons/hicolor/16x16/apps/cups.png
/usr/share/icons/hicolor/32x32/apps/cups.png
/usr/share/icons/hicolor/64x64/apps/cups.png
/usr/share/locale/ca/cups_ca.po
/usr/share/locale/cs/cups_cs.po
/usr/share/locale/da/cups_da.po
/usr/share/locale/de/cups_de.po
/usr/share/locale/en/cups_en.po
/usr/share/locale/es/cups_es.po
/usr/share/locale/fr/cups_fr.po
/usr/share/locale/it/cups_it.po
/usr/share/locale/ja/cups_ja.po
/usr/share/locale/pt_BR/cups_pt_BR.po
/usr/share/locale/ru/cups_ru.po
/usr/share/locale/zh_CN/cups_zh_CN.po
/usr/share/pam.d/cups

%files dev
%defattr(-,root,root,-)
/usr/include/cups/adminutil.h
/usr/include/cups/array.h
/usr/include/cups/backend.h
/usr/include/cups/cups.h
/usr/include/cups/dir.h
/usr/include/cups/file.h
/usr/include/cups/http.h
/usr/include/cups/ipp.h
/usr/include/cups/language.h
/usr/include/cups/ppd.h
/usr/include/cups/pwg.h
/usr/include/cups/raster.h
/usr/include/cups/sidechannel.h
/usr/include/cups/transcode.h
/usr/include/cups/versioning.h
/usr/lib64/libcups.so
/usr/lib64/libcupsimage.so
/usr/lib64/pkgconfig/cups.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/cups/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcups.so.2
/V3/usr/lib64/libcupsimage.so.2
/usr/lib64/libcups.so.2
/usr/lib64/libcupsimage.so.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cups/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/cups/3e1353f170c05e116354014b1f59a7dfbddc4d87
/usr/share/package-licenses/cups/ba086bb20e20708223f0e789026aabeb7c6ae0cc

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cancel.1
/usr/share/man/man1/cups-config.1
/usr/share/man/man1/cups.1
/usr/share/man/man1/cupstestppd.1
/usr/share/man/man1/ippeveprinter.1
/usr/share/man/man1/ipptool.1
/usr/share/man/man1/lp.1
/usr/share/man/man1/lpoptions.1
/usr/share/man/man1/lpq.1
/usr/share/man/man1/lpr.1
/usr/share/man/man1/lprm.1
/usr/share/man/man1/lpstat.1
/usr/share/man/man1/ppdc.1
/usr/share/man/man1/ppdhtml.1
/usr/share/man/man1/ppdi.1
/usr/share/man/man1/ppdmerge.1
/usr/share/man/man1/ppdpo.1
/usr/share/man/man5/classes.conf.5
/usr/share/man/man5/client.conf.5
/usr/share/man/man5/cups-files.conf.5
/usr/share/man/man5/cups-snmp.conf.5
/usr/share/man/man5/cupsd-logs.5
/usr/share/man/man5/cupsd.conf.5
/usr/share/man/man5/ipptoolfile.5
/usr/share/man/man5/mailto.conf.5
/usr/share/man/man5/mime.convs.5
/usr/share/man/man5/mime.types.5
/usr/share/man/man5/ppdcfile.5
/usr/share/man/man5/printers.conf.5
/usr/share/man/man5/subscriptions.conf.5
/usr/share/man/man7/backend.7
/usr/share/man/man7/filter.7
/usr/share/man/man7/ippevepcl.7
/usr/share/man/man7/ippeveps.7
/usr/share/man/man7/notifier.7
/usr/share/man/man8/cups-deviced.8
/usr/share/man/man8/cups-driverd.8
/usr/share/man/man8/cups-exec.8
/usr/share/man/man8/cups-lpd.8
/usr/share/man/man8/cups-snmp.8
/usr/share/man/man8/cupsaccept.8
/usr/share/man/man8/cupsctl.8
/usr/share/man/man8/cupsd-helper.8
/usr/share/man/man8/cupsd.8
/usr/share/man/man8/cupsdisable.8
/usr/share/man/man8/cupsenable.8
/usr/share/man/man8/cupsfilter.8
/usr/share/man/man8/cupsreject.8
/usr/share/man/man8/lpadmin.8
/usr/share/man/man8/lpc.8
/usr/share/man/man8/lpinfo.8
/usr/share/man/man8/lpmove.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/sockets.target.wants/cups.socket
/usr/lib/systemd/system/cups-lpd.socket
/usr/lib/systemd/system/cups-lpd@.service
/usr/lib/systemd/system/cups.path
/usr/lib/systemd/system/cups.service
/usr/lib/systemd/system/cups.socket
